# Generated by Django 4.0.2 on 2022-03-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor', models.CharField(max_length=32)),
                ('amount', models.FloatField()),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
