# Generated by Django 4.0.2 on 2022-03-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmdr_crowfunding_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='department',
            field=models.CharField(choices=[('ALIM', 'Alimentos'), ('ASIS_MED', 'Asis Medica'), ('EDUC', 'Educ')], default='ALIM', max_length=12),
            preserve_default=False,
        ),
    ]
