# Generated by Django 4.0.2 on 2022-03-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmdr_crowfunding_app', '0002_donation_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
