# Generated by Django 4.0.2 on 2022-03-05 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmdr_crowfunding_app', '0003_alter_donation_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default=25, max_length=3),
            preserve_default=False,
        ),
    ]
