# Generated by Django 4.0.2 on 2022-03-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jmdr_crowfunding_app', '0004_donation_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(choices=[('ALIM', 'Alimentos'), ('ASIS_MED', 'Asis Medica'), ('EDUC', 'Educ')], max_length=12)),
            ],
        ),
    ]
